-- Run this if Supabase says: column customer.id does not exist
-- It adds running-number IDs to existing tables without dropping data.

alter table public.customer
  add column if not exists id bigint generated by default as identity;

alter table public."order"
  add column if not exists id bigint generated by default as identity;

alter table public.order_item
  add column if not exists id bigint generated by default as identity;

alter table public.delivery_info
  add column if not exists id bigint generated by default as identity;

alter table public.attachments
  add column if not exists id bigint generated by default as identity;

alter table public.flower_types
  add column if not exists id bigint generated by default as identity;

alter table public.paper_colors
  add column if not exists id bigint generated by default as identity;

alter table public.bow_colors
  add column if not exists id bigint generated by default as identity;

alter table public.rose_colors
  add column if not exists id bigint generated by default as identity;

alter table public.lily_colors
  add column if not exists id bigint generated by default as identity;

create unique index if not exists customer_id_key on public.customer(id);
create unique index if not exists order_id_key on public."order"(id);
create unique index if not exists order_item_id_key on public.order_item(id);
create unique index if not exists delivery_info_id_key on public.delivery_info(id);
create unique index if not exists attachments_id_key on public.attachments(id);
create unique index if not exists flower_types_id_key on public.flower_types(id);
create unique index if not exists paper_colors_id_key on public.paper_colors(id);
create unique index if not exists bow_colors_id_key on public.bow_colors(id);
create unique index if not exists rose_colors_id_key on public.rose_colors(id);
create unique index if not exists lily_colors_id_key on public.lily_colors(id);

notify pgrst, 'reload schema';
