-- Development reset: this recreates the order tables with running-number IDs.
-- Do not run this on production data unless you are okay with deleting these tables.

drop table if exists public.attachments cascade;
drop table if exists public.delivery_info cascade;
drop table if exists public."order" cascade;
drop table if exists public.customer cascade;
drop table if exists public.flower_types cascade;
drop table if exists public.paper_colors cascade;
drop table if exists public.bow_colors cascade;
drop table if exists public.rose_colors cascade;
drop table if exists public.lily_colors cascade;
drop sequence if exists public.order_no_seq;

create sequence public.order_no_seq start with 1 increment by 1;

create table public.customer (
  id bigint generated by default as identity primary key,
  line_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table public."order" (
  id bigint generated by default as identity primary key,
  order_no bigint not null unique default nextval('public.order_no_seq'),
  customer_id bigint references public.customer(id),
  items jsonb not null default '[]'::jsonb,
  pickup_mode text,
  delivery_date date,
  delivery_time time,
  paper_color text,
  bow_color text,
  bouquet_price numeric,
  has_card boolean not null default false,
  card_message text,
  created_at timestamptz not null default now()
);

create table public.delivery_info (
  id bigint generated by default as identity primary key,
  order_id bigint references public."order"(id) on delete cascade,
  recipient_name text,
  recipient_phone text,
  address text,
  map_link text,
  delivery_price numeric,
  created_at timestamptz not null default now()
);

create table public.attachments (
  id bigint generated by default as identity primary key,
  order_id bigint references public."order"(id) on delete cascade,
  label text,
  file_name text,
  src text,
  created_at timestamptz not null default now()
);

create table public.flower_types (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamptz not null default now()
);

create table public.paper_colors (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamptz not null default now()
);

create table public.bow_colors (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamptz not null default now()
);

create table public.rose_colors (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamptz not null default now()
);

create table public.lily_colors (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamptz not null default now()
);

insert into public.flower_types (name)
values
  ('กุหลาบ'),
  ('ทานตะวัน'),
  ('ลิลลี่'),
  ('ไฮเดรนเยีย')
on conflict (name) do nothing;

insert into public.paper_colors (name)
values
  ('Crimson'),
  ('Amber'),
  ('Velvet'),
  ('ขาว'),
  ('ชมพู'),
  ('น้ำตาล')
on conflict (name) do nothing;

insert into public.bow_colors (name)
values
  ('Crimson'),
  ('Amber'),
  ('Velvet'),
  ('ขาว'),
  ('ชมพู'),
  ('ทอง')
on conflict (name) do nothing;

insert into public.rose_colors (name)
values
  ('แดง'),
  ('ขาว'),
  ('ชมพู'),
  ('เหลือง')
on conflict (name) do nothing;

insert into public.lily_colors (name)
values
  ('ขาว'),
  ('ชมพู'),
  ('เหลือง'),
  ('ส้ม')
on conflict (name) do nothing;

alter table public.customer enable row level security;
alter table public."order" enable row level security;
alter table public.delivery_info enable row level security;
alter table public.attachments enable row level security;
alter table public.flower_types enable row level security;
alter table public.paper_colors enable row level security;
alter table public.bow_colors enable row level security;
alter table public.rose_colors enable row level security;
alter table public.lily_colors enable row level security;

create policy "Allow public insert customer"
  on public.customer
  for insert
  to anon
  with check (true);

create policy "Allow public read customer"
  on public.customer
  for select
  to anon
  using (true);

create policy "Allow public insert order"
  on public."order"
  for insert
  to anon
  with check (true);

create policy "Allow public read order"
  on public."order"
  for select
  to anon
  using (true);

create policy "Allow public insert delivery_info"
  on public.delivery_info
  for insert
  to anon
  with check (true);

create policy "Allow public read delivery_info"
  on public.delivery_info
  for select
  to anon
  using (true);

create policy "Allow public insert attachments"
  on public.attachments
  for insert
  to anon
  with check (true);

create policy "Allow public read attachments"
  on public.attachments
  for select
  to anon
  using (true);

create policy "Allow public read flower_types"
  on public.flower_types
  for select
  to anon
  using (true);

create policy "Allow public read paper_colors"
  on public.paper_colors
  for select
  to anon
  using (true);

create policy "Allow public read bow_colors"
  on public.bow_colors
  for select
  to anon
  using (true);

create policy "Allow public read rose_colors"
  on public.rose_colors
  for select
  to anon
  using (true);

create policy "Allow public read lily_colors"
  on public.lily_colors
  for select
  to anon
  using (true);

notify pgrst, 'reload schema';
