import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai_Looped, Inter } from "next/font/google";
import "./globals.css";
import Navbar2 from "@/components/navbar/Navbar2";
import Providers from "./providers";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const notoSansThaiLooped = Noto_Sans_Thai_Looped({
  variable: "--font-noto-sans-thai-looped",
  subsets: ["latin", "thai"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Sweet Pea & Co.",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "Sweet Pea & Co.",
  icons: {
    icon: "/SweetPea&Co_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={cn("font-sans", inter.variable)}>
      <body className={` ${notoSansThaiLooped.className} antialiased`}>
        <Providers>
          <div className="flex min-h-screen bg-[#faf9f7] dark:bg-[#161d18]">
            <Navbar2 />
            <div className="min-w-0 flex-1">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
