import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai_Looped } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Navbar2 from "@/components/navbar/Navbar2";

const notoSansThaiLooped = Noto_Sans_Thai_Looped({
  variable: "--font-noto-sans-thai-looped",
  subsets: ["latin", "thai"],
});

const thisyear = new Date().getFullYear();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Florist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={` ${notoSansThaiLooped.className} antialiased`}
      >
        <Navbar2 />
        {children}
        <footer className="p-4 text-center text-sm text-gray-500">
          &copy; {thisyear} Florist. All rights reserved. Powered by Next.js. from Job and Ohmyim
        </footer>
      </body>
    </html>
  );
}
